project:
  type: website

website:
  title: "Ismail Mohammed"
  repo-url: https://github.com/quarto-dev/quarto-demo
  repo-actions: [edit, issue]
  google-analytics:
    tracking-id: "G-6GL9ZFETVN"
    storage: none
  page-footer:
    right:
      - icon: github
        href: https://github.com/ismailmo1
      - icon: linkedin
        href: https://linkedin.com/in/ismailmo-chem
  body-footer: |
    Any thoughts, comments or ideas? Please let me know [here](mailto:ismailmo4@gmail.com)!
  # comments:
  #   giscus:
  #     repo: https://github.com/ismailmo1/blog/
  open-graph: true
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ismailmo1
      - icon: linkedin
        href: https://linkedin.com/in/ismailmo-chem
listing:
  default
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
execute:
  freeze: auto
